<div class="promo-banners">
    <a href="#"><img src="https://img.freepik.com/premium-vector/super-discount-sale-promo-banner-template_419341-1280.jpg?w=2000" alt="banner1" /></a>
    <a href="#"><img src="https://img.freepik.com/vetores-premium/banner-anunciando-mega-desconto-com-metade-do-preco_419341-8.jpg?w=2000" alt="banner2" /></a>
    <a href="#"><img src="https://img.freepik.com/vetores-premium/etiqueta-de-desconto-com-oferta-promocional_419341-1099.jpg?w=2000" alt="banner3" /></a>
    <a href="#"><img src="https://img.freepik.com/premium-vector/discount-banner-promoting-special-offer-with-price-reduction-sale-website-header-advertising-wholesale-up-70-percent-off-shopping-vector-illustration_419341-637.jpg?w=2000" alt="banner4" /></a>
</div>