<div class="info">
    <div class="free-shipping">
        <span class="fa-solid fa-truck-fast fa-3x"></span>
        <p>frete grátis em compras acima de R$200</p>
    </div>
    <div class="discount">
        <span class="fa-solid fa-file-invoice-dollar fa-3x"></span>
        <p>desconto de 5% no boleto</p>
    </div>
    <div class="installment">
        <span class="fa-solid fa-credit-card fa-3x"></span>
        <p>parcele em até 12 vezes sem juros</p>
    </div>
    <div class="safe-purchase">
        <span class="fa-solid fa-shield-halved fa-3x"></span>
        <p>compra segura</p>
    </div>
</div>